---
version: 2
updates:
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    pull-request-branch-name:
      separator: "/"
    reviewers:
      - "@jensen95"
  - package-ecosystem: "npm"
    versioning-strategy: increase
    directory: "/packages/**/*"
    schedule:
      interval: "daily"
    labels:
      - "dependencies"
    open-pull-requests-limit: 100
    reviewers:
      - "@jensen95"
    pull-request-branch-name:
      separator: "-"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
