name: Bump changeset version on dependency update

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  bump:
    name: Bump changesets version on dependency update
    if:  startsWith(github.head_ref, 'dependabot-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changes
        run: |
          git diff HEAD^^  --name-only --diff-filter=AM | grep -E 'package.json' | xargs -I {} dirname {} | sort | uniq > changed-packages.txt
          cat changed-packages.txt

      - name: Create changeset version file
        run: |
          changeset=.changeset/$(echo $GITHUB_REF | sed 's/refs\/heads\///').md
          # changeset=.changeset/$(date +%Y-%m-%d-%H-%M-%S)-dependabot.md
          rm -f $changeset
          touch $changeset
          echo "---" >> $changeset

          while read dir; do
            cd $dir
            echo "Bumping changeset version for $dir"
            # get package name from package.json
            name=$(node -p "require('./package.json').name")
            cd -
            echo "\"$name\": patch" >> $changeset
          done < changed-packages.txt

          echo "---" >> $changeset
          echo "" >> $changeset
          git log -1 --pretty=%s >> $changeset
          echo "" >> $changeset

          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add $changeset
          git commit --amend --no-edit
          git push -f
